#!/usr/bin/env python3
"""Remove only files generated by this project's pipeline."""

from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
GENERATED = [
    "data/raw/customers.csv",
    "data/raw/loans.csv",
    "data/raw/monthly_performance.csv",
    "data/raw/manifest.json",
    "data/processed/credit_risk.db",
    "artifacts/model.json",
    "artifacts/model_metrics.json",
    "artifacts/model_coefficients.csv",
    "artifacts/scored_snapshots.csv",
    "artifacts/dashboard_preview.svg",
    "artifacts/charts/portfolio_risk_trend.svg",
    "artifacts/charts/feature_importance.svg",
    "artifacts/charts/holdout_calibration.svg",
    "artifacts/charts/latest_risk_tier_exposure.svg",
    "reports/executive_summary.md",
    "reports/model_card.md",
    "reports/sql_results.md",
]


def main() -> None:
    removed = 0
    for relative in GENERATED:
        path = REPO_ROOT / relative
        if path.exists():
            path.unlink()
            removed += 1
    print(f"Removed {removed} generated files.")


if __name__ == "__main__":
    main()

